<?xml version="1.0" encoding="utf-8" standalone="yes"?>
<rss version="2.0" xmlns:atom="http://www.w3.org/2005/Atom">
  <channel>
    <title>jboss on Miro&#39;s World</title>
    <link>https://miroadamy.com/tags/jboss/</link>
    <description>Recent content in jboss on Miro&#39;s World</description>
    <generator>Hugo -- gohugo.io</generator>
    <language>en</language>
    <lastBuildDate>Sat, 11 Apr 2015 11:22:48 +0800</lastBuildDate>
    
	<atom:link href="https://miroadamy.com/tags/jboss/index.xml" rel="self" type="application/rss+xml" />
    
    
    <item>
      <title>Fixing the shutdown problem with JBoss</title>
      <link>https://miroadamy.com/posts/2015-04-11-jboss-shutdown/</link>
      <pubDate>Sat, 11 Apr 2015 11:22:48 +0800</pubDate>
      
      <guid>https://miroadamy.com/posts/2015-04-11-jboss-shutdown/</guid>
      <description>Observed at QA environment. During automated shutdown sequence, the exception was thrown:
1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27  $ bin/gdi-qa-com1.sh stop JBOSS_CMD_STOP = java -classpath /opt/jboss/jboss-as/bin/shutdown.jar:/opt/jboss/jboss-as/client/jnet.jar org.jboss.Shutdown --shutdown --user=admin --password=admin -s jnp://0.0.0.0:1099 Exception in thread &amp;#34;main&amp;#34; javax.naming.CommunicationException: Could not obtain connection to any of these urls: 0.0.0.0:1099 [Root exception is javax.</description>
    </item>
    
  </channel>
</rss>